x-networks: &networks
  - net-internal
  - net-external
services:
  srv01:
    build: .
    container_name: srv01
    hostname: srv01
    volumes:
      - ./keys/srv01.pub:/root/.ssh/authorized_keys
    cap_add:
      - NET_ADMIN
    ports:
      - 6001:22
    networks: *networks

  client01:
    build: .
    container_name: client01
    hostname: client01
    volumes:
      - ./keys/client01.pub:/root/.ssh/authorized_keys
    cap_add:
      - NET_ADMIN
    ports:
      - 6002:22
    networks: *networks

  client02:
    build: .
    container_name: client02
    hostname: client02
    volumes:
      - ./keys/client02.pub:/root/.ssh/authorized_keys
    cap_add:
      - NET_ADMIN
    ports:
      - 6003:22
    networks: *networks

networks:
  net-internal:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1

  net-external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24
          gateway: 10.100.0.1
